[package]
name = "updater"
version = "0.1.0"
authors = ["snsvrno <snsvrno@tuta.io>"]

[dependencies]
version = { git = "https://github.com/Snsvrno/version-lp-rs", tag = "0.1.5" }
lperror = { git = "https://github.com/Snsvrno/errors-lp-rs", tag = "0.1.0"}

restson = "^0.2"
serde = "^1.0"
serde_derive = "^1.0"
ansi_term = "0.10.2"

regex = "1.0.0"

log = "0.4.2"